global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: "monitoring-stack"
    env: "production"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      timeout: 10s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: instance
        replacement: "${1}"

  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://github.com
          - https://google.com
        labels:
          env: external
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox-icmp
    metrics_path: /probe
    params:
      module:
        - icmp
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
        labels:
          env: external
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
